apiVersion: v2
name: "mcp-server-aws-documentation"
description: "A Helm chart for AWS documentation access with search, content recommendations, and markdown conversion"
home: https://github.com/awslabs/mcp/tree/HEAD/src/aws-documentation-mcp-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/awslabs/mcp/tree/HEAD/src/aws-documentation-mcp-server
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-aws-documentation/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "1.0.2"
keywords:
  - mcp-server-aws-documentation
  - mcp-server
  - remote
  - research
  - integration
