apiVersion: v2
name: "mcp-server-neo4j-memory"
description: A Helm chart for Provides persistent memory capabilities through Neo4j graph database integration.
home: https://github.com/neo4j-contrib/mcp-neo4j
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/neo4j-contrib/mcp-neo4j
icon: https://raw.githubusercontent.com/modelcontextprotocol/docs/refs/heads/main/favicon.svg
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: 0.1.3
keywords:
  - mcp-server-neo4j-memory
  - mcp-server
  - remote
  - database
  - integration
