apiVersion: v2
name: "mcp-server-neo4j-memory"
description: "A Helm chart for Provides persistent memory capabilities through Neo4j graph database integration."
home: https://github.com/neo4j-contrib/mcp-neo4j/tree/HEAD/servers/mcp-neo4j-memory
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/neo4j-contrib/mcp-neo4j/tree/HEAD/servers/mcp-neo4j-memory
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-neo4j-memory/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "0.1.4"
keywords:
  - mcp-server-neo4j-memory
  - mcp-server
  - remote
  - database
  - integration
