apiVersion: v2
name: "mcp-server-aws-synthetic-data"
description: "A Helm chart for Generate, validate, and manage synthetic data with pandas code execution and S3 integration"
home: https://github.com/awslabs/mcp/tree/HEAD/src/syntheticdata-mcp-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/awslabs/mcp/tree/HEAD/src/syntheticdata-mcp-server
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-aws-synthetic-data/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "1.0.1"
keywords:
  - mcp-server-aws-synthetic-data
  - mcp-server
  - remote
  - development
  - storage
