apiVersion: v2
name: "mcp-server-paypal"
description: "A Helm chart for A Model Context Protocol (MCP) server that enables AI models to interact with PayPal Apis."
home: https://github.com/paypal/agent-toolkit
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/paypal/agent-toolkit
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-paypal/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "0.3.4"
keywords:
  - mcp-server-paypal
  - mcp-server
  - remote
  - development
  - integration
  - finance
