apiVersion: v2
name: "mcp-server-e2b"
description: A Helm chart for Adds code interpreting capabilities to the Claude Desktop app.
home: https://github.com/e2b-dev/mcp-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/e2b-dev/mcp-server
icon: https://raw.githubusercontent.com/modelcontextprotocol/docs/refs/heads/main/favicon.svg
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: 0.2.0
keywords:
  - mcp-server-e2b
  - mcp-server
  - remote
  - automation
  - development
