apiVersion: v2
name: "mcp-server-kubernetes"
description: "A Helm chart for Typescript implementation of Kubernetes cluster operations for pods, deployments, services."
home: https://github.com/Flux159/mcp-server-kubernetes
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/Flux159/mcp-server-kubernetes
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-kubernetes/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "2.3.1"
keywords:
  - mcp-server-kubernetes
  - mcp-server
  - native
  - development
  - integration
  - cloud
