apiVersion: v2
name: "mcp-server-commands"
description: "A Helm chart for Run any command with `run_command` and `run_script` tools."
home: https://github.com/g0t4/mcp-server-commands
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/g0t4/mcp-server-commands
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-commands/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: 0.5.0
keywords:
  - mcp-server-commands
  - mcp-server
  - standalone
  - development
  - automation
