
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          {{- range .Values.args }}
            - {{ . }}
          {{- end }}
          env:
          {{- include "minibridge.env" . | nindent 12}}
            - name: VALKEY_HOST
              value: {{ .Values.env.VALKEY_HOST}}
            - name: VALKEY_PORT
              value: {{ .Values.env.VALKEY_PORT}}
            - name: VALKEY_USERNAME
              value: {{ .Values.env.VALKEY_USERNAME}}
            - name: VALKEY_PWD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.VALKEY_PWD.valueFrom.name | default (printf "%s-secrets" (include "base.fullname" .) ) }}"
                  key: "{{ .Values.secrets.VALKEY_PWD.valueFrom.key | default "VALKEY_PWD" }}"
            - name: VALKEY_USE_SSL
              value: {{ .Values.env.VALKEY_USE_SSL}}
            - name: VALKEY_CERT_REQS
              value: {{ .Values.env.VALKEY_CERT_REQS}}
            - name: VALKEY_CA_PATH
              value: {{ .Values.env.VALKEY_CA_PATH}}
            - name: VALKEY_SSL_KEYFILE
              value: {{ .Values.env.VALKEY_SSL_KEYFILE}}
            - name: VALKEY_SSL_CERTFILE
              value: {{ .Values.env.VALKEY_SSL_CERTFILE}}
            - name: VALKEY_CA_CERTS
              value: {{ .Values.env.VALKEY_CA_CERTS}}
            - name: VALKEY_CLUSTER_MODE
              value: {{ .Values.env.VALKEY_CLUSTER_MODE}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf  "%s-%s" .Chart.Version .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: health
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "base.fullname" . }}-sandbox
              mountPath: /tmp
            - name: {{ include "base.fullname" . }}-secrets
              mountPath: /secrets/
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "base.fullname" . }}-sandbox
          emptyDir: {}
        - name: {{ include "base.fullname" . }}-secrets
          secret:
            secretName: {{ include "base.fullname" . }}-secrets
            items:
              {{- include "minibridge.items" .  | nindent 14 }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
