apiVersion: v2
name: "mcp-server-base"
description: A Helm chart for Base Network integration for onchain tools, allowing interaction with Base Network and Coinbase API for wallet management, fund transfers, smart contracts, and DeFi operations.
home: https://github.com/base/base-mcp
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/base/base-mcp
icon: https://raw.githubusercontent.com/modelcontextprotocol/docs/refs/heads/main/favicon.svg
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: 1.0.13
keywords:
  - mcp-server-base
  - mcp-server
  - remote
  - integration
  - finance
