apiVersion: v2
name: "mcp-server-circleci"
description: "A Helm chart for Enable AI Agents to fix build failures from CircleCI."
home: https://github.com/CircleCI-Public/mcp-server-circleci
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/CircleCI-Public/mcp-server-circleci
icon: https://raw.githubusercontent.com/modelcontextprotocol/docs/refs/heads/main/favicon.svg
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: 0.7.1
keywords:
  - mcp-server-circleci
  - mcp-server
  - remote
  - development
