apiVersion: v2
name: "mcp-server-alation"
description: "A Helm chart for Access Alation Data Catalog metadata and context for AI agents via MCP server."
home: https://github.com/Alation/alation-ai-agent-sdk
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/Alation/alation-ai-agent-sdk
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-alation/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "0.3.0"
keywords:
  - mcp-server-alation
  - mcp-server
  - remote
  - database
  - research
