apiVersion: v2
name: "mcp-server-aws-documentdb"
description: "A Helm chart for AWS DocumentDB MCP server for querying and managing MongoDB-compatible document databases"
home: https://github.com/awslabs/mcp/tree/HEAD/src/documentdb-mcp-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/awslabs/mcp/tree/HEAD/src/documentdb-mcp-server
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-aws-documentdb/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "1.0.1"
keywords:
  - mcp-server-aws-documentdb
  - mcp-server
  - remote
  - database
  - cloud
