apiVersion: v2
name: "mcp-server-amass"
description: "A Helm chart for Advanced subdomain enumeration and reconnaissance tool with MCP interface"
home: https://github.com/cyproxio/mcp-for-security/tree/HEAD/amass-mcp
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/cyproxio/mcp-for-security/tree/HEAD/amass-mcp
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-amass/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "6190e55"
keywords:
  - mcp-server-amass
  - mcp-server
  - native
  - security
