apiVersion: v2
name: "mcp-server-aws-neptune"
description: "A Helm chart for Amazon Neptune graph database server for openCypher and Gremlin queries"
home: https://github.com/awslabs/mcp/tree/HEAD/src/amazon-neptune-mcp-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/awslabs/mcp/tree/HEAD/src/amazon-neptune-mcp-server
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-aws-neptune/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "1.0.1"
keywords:
  - mcp-server-aws-neptune
  - mcp-server
  - remote
  - database
  - cloud
