apiVersion: v2
name: "mcp-server-hyperbrowser"
description: "A Helm chart for Scrapes, extracts data, and automates web page interactions."
home: https://github.com/hyperbrowserai/mcp
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/hyperbrowserai/mcp
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-hyperbrowser/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "1.0.25"
keywords:
  - mcp-server-hyperbrowser
  - mcp-server
  - remote
  - web
  - automation
