apiVersion: v2
name: "mcp-server-browserstack"
description: "A Helm chart for Access BrowserStack's Test Platform to debug, write and fix tests, do accessibility testing."
home: https://github.com/browserstack/mcp-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/browserstack/mcp-server
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-browserstack/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "1.1.6"
keywords:
  - mcp-server-browserstack
  - mcp-server
  - remote
  - automation
  - development
