apiVersion: v2
name: "mcp-server-aws-timestream-influxdb"
description: "A Helm chart for Manage AWS Timestream for InfluxDB instances, clusters, parameter groups and query time-series data"
home: https://github.com/awslabs/mcp/tree/HEAD/src/timestream-for-influxdb-mcp-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/awslabs/mcp/tree/HEAD/src/timestream-for-influxdb-mcp-server
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-aws-timestream-influxdb/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "0.0.1"
keywords:
  - mcp-server-aws-timestream-influxdb
  - mcp-server
  - remote
  - database
  - cloud
