apiVersion: v2
name: "mcp-server-google-bigquery"
description: "A Helm chart for A server that lets your LLM securely query BigQuery."
home: https://github.com/ergut/mcp-bigquery-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/ergut/mcp-bigquery-server
icon: https://raw.githubusercontent.com/modelcontextprotocol/docs/refs/heads/main/favicon.svg
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: 1.0.3
keywords:
  - mcp-server-google-bigquery
  - mcp-server
  - remote
  - integration
  - database
  - development
