apiVersion: v2
name: "mcp-server-attio"
description: "A Helm chart for Allows AI clients to manage records and notes in Attio CRM."
home: https://github.com/hmk/attio-mcp-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/hmk/attio-mcp-server
icon: "https://raw.githubusercontent.com/acuvity/mcp-servers-registry/refs/heads/main/mcp-server-attio/logo.png"
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: "0.0.2"
keywords:
  - mcp-server-attio
  - mcp-server
  - remote
  - integration
