apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "base.fullname" . }}-secrets
data:
{{- include "minibridge.secrets" .}}
{{- range $k, $v := .Values.secrets}}
    {{- if and (not $v.value) (not $v.valueFrom.name) }}
      {{ required (printf "required value for secrets.%s either as .value or .valueFrom.name and .valueFrom.key" $k) $v.value}}
    {{- end }}
    {{- if $v.value}}
    {{$k }}: {{$v.value | b64enc | quote }}
    {{- end }}
{{- end }}
