apiVersion: v2
name: "mcp-server-gyazo"
description: "A Helm chart for Integrates Gyazo images for AI assistants via Model Context Protocol."
home: https://github.com/nota/gyazo-mcp-server
sources:
  - https://github.com/acuvity/mcp-servers-registry
  - https://github.com/nota/gyazo-mcp-server
icon: https://raw.githubusercontent.com/modelcontextprotocol/docs/refs/heads/main/favicon.svg
type: application
maintainers:
  - name: Acuvity
    email: support@acuvity.ai
version: 1.0.0
appVersion: 0.1.0
keywords:
  - mcp-server-gyazo
  - mcp-server
  - remote
  - web
  - integration
