name: Build & Deploy MCP Servers Site

on:
  push:
    branches:
      - main

permissions:
  contents: read       # checkout
  pages: write         # publish
  id-token: write      # for deploy authentication

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Generate the aggregated mcp-servers.json
      - name: Generate mcp-servers.json
        run: |
          WEBSITE_DIR=assets/website
          mkdir -p "$WEBSITE_DIR"

          # 2a) Slurp all card.json files into a temp array
          TMP=$(mktemp)
          find . -maxdepth 1 -type d -name 'mcp-server*' | while read DIR; do
            CARD="$DIR/card.json"
            [ -f "$CARD" ] && cat "$CARD"
          done | jq -s '.' > "$TMP"

          # 2b) Merge discovery.json (base) with cards overrides
          jq -s '
            .[0] as $disc |
            .[1] as $cards |
            $disc
            | map( (. as $d
                     | ($cards[]? | select(.id == $d.id))
                     // $d
                   ) )
          ' "$WEBSITE_DIR/discovery.json" "$TMP" \
          > "$WEBSITE_DIR/mcp-servers.json"

          rm "$TMP"
          echo "✓ Generated $(jq length "$WEBSITE_DIR/mcp-servers.json") entries in mcp-servers.json"

      # 3. Upload the website folder as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: assets/website

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
