# .github/workflows/deploy-pages.yml
name: Build & Deploy MCP Servers Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read       # for checkout / reading discovery.json
  pages: write         # for publishing
  id-token: write      # for authentication

jobs:
  build:
    name: Build mcp-servers.json & Upload Artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate mcp-servers.json
        run: |
          WEBSITE_DIR=assets/website
          mkdir -p "$WEBSITE_DIR"

          # 1) Gather all card.json files into a temp array
          TMP=$(mktemp)
          find . -maxdepth 1 -type d -name 'mcp-server*' | while read DIR; do
            CARD="$DIR/card.json"
            [ -f "$CARD" ] && cat "$CARD"
          done | jq -s '.' > "$TMP"

          # 2) Merge: cards override discovery, but keep any discovery-only entries
          jq -s '
            # .[0] = discovery array, .[1] = cards array
            (.[1] + .[0])
            | unique_by(.id)
          ' assets/website/discovery.json "$TMP" \
            > assets/website/mcp-servers.json

          rm "$TMP"
          echo "✓ Generated $(jq length assets/website/mcp-servers.json) server entries."

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: assets/website

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
